### ISSUE TITLE
[A Mod Issue] Awesome Dungeon / Awesome Dungeon Ocean / Awesome Dungeon Nether / Awesome Dungeon End

### ISSUE THREAD

**Issue by IntoSky0405** [IntoSky0405/Explore-Modpack#1]
### An error :

```
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Replace mod 'Library Ferret' (libraryferret) 2.5.1 with version 2.0.0.
Unmet dependency listing:
	 - Mod 'Awesome Dungeon' (awesomedungeon) 2.0.11 requires version 2.0.0 of mod 'Library Ferret' (libraryferret), but only the wrong version is present: 2.5.1!
	 - Mod 'Awesome Dungeon Edition end' (awesomedungeonend) 1.0.3 requires version 2.0.0 of mod 'Library Ferret' (libraryferret), but only the wrong version is present: 2.5.1!
	 - Mod 'Awesome Dungeon Edition Nether' (awesomedungeonnether) 1.0.3 requires version 2.0.0 of mod 'Library Ferret' (libraryferret), but only the wrong version is present: 2.5.1!
	 - Mod 'Awesome Dungeon Edition Ocean' (awesomedungeonocean) 2.0.8 requires version 2.0.0 of mod 'Library Ferret' (libraryferret), but only the wrong version is present: 2.5.1!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
```

Explore Version : Alpha 0.3

**Comment by IntoSky0405** [comment]
### Reason :
Awesome Dungeon's fabric.mod.json was error
### Solution :
Revise fabric.mod.json :
`{"schemaVersion":1,"depends":{"minecraft":"~1.19","java":">=17","libraryferret":">=2.0.0","fabric":"*","fabricloader":">=0.14.6"},"icon":"assets/awesomedungeon/icon.png","description":"This mod add awesome dungeons (structure) in your world !","version":"2.0.11","license":"ARR","environment":"*","mixins":[],"contact":{"homepage":"https://www.curseforge.com/minecraft/mc-mods/awesome-dungeon-fabric"},"name":"Awesome Dungeon","entrypoints":{"main":["awesomedungeon.Main"]},"id":"awesomedungeon","authors":["JTL Elisa from JTorLeon Studios"]}`

_"libraryferret":"2.0.0"_ -> _"libraryferret":">=2.0.0"_
